---
- import_tasks: roles/mac/homebrew/tasks/brew.yml
  vars:
    pkgs:
      - name: imagemagick
      - name: opencv
  tags:
    - image_processing

- import_tasks: roles/mac/homebrew/tasks/cask.yml
  vars:
    pkgs:
      - gimp
      - vlc
  tags:
    - image_processing

- import_tasks: roles/mac/mas/tasks/mas.yml
  vars:
    apps:
      - appid: "414298354"
        name: ToyViewer
      - appid: "540348655"
        name: Monosnap
  tags:
    - image_processing

- import_tasks: roles/python3/tasks/pip.yml
  vars:
    pkgs:
      - matplotlib
  tags:
    - image_processing
