---
- import_tasks: roles/mac/homebrew/tasks/brew.yml
  vars:
    pkgs:
      - name: doxygen
      - name: graphviz
      - name: pandoc
  tags:
    - documentation

# エラー終了するがインストールはされている？
# - import_tasks: roles/mac/homebrew/tasks/cask.yml
#   vars:
#     pkgs:
#       - name: java
#   tags:
#     - documentation

# no longer avialable on App Store
# - import_tasks: roles/mac/mas/tasks/mas.yml
#   vars:
#     apps:
#       - appid: "448925439"
#         name: Marked
#   tags:
#     - documentation

- import_tasks: roles/ruby/tasks/gem.yml
  vars:
    gems:
      - asciidoctor
      - asciidoctor-diagram
      - name: asciidoctor-pdf
        pre_release: yes
      - asciidoctor-pdf-cjk
      - kramdown
      - pygments.rb
  tags:
    - documentation

- import_tasks: roles/python3/tasks/pip.yml
  vars:
    pkgs:
      - Sphinx
  tags:
    - documentation
