---
- name: Ensure RubyGems are installed.
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(omit) }}"
    pre_release: "{{ item.pre_release | default(omit) }}"
    build_flags: "{{ item.build_flags | default(omit) }}"
    user_install: "{{ gem_user_install | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  become: yes
  with_items: "{{ gems }}"
